int Hooked_Initialize( cl_enginefunc_t *ppEnginefuncs, int iVersion );
int Hooked_HUD_Redraw(float a, int b);
void Hooked_V_CalcRefdef( struct ref_params_s *pparams );
int Hooked_HUD_AddEntity(int type, struct cl_entity_s *ent, const char* modelname);
void Hooked_HUD_PlayerMove( struct playermove_s *pPmove, int server);
void Hooked_CL_CreateMove(float frametime, struct usercmd_s *cmd, int active);
void Hooked_HUD_Key_Event( int eventcode, int keynum, const char *pszCurrentBinding );
void Hooked_HUD_PostRunCmd( struct local_state_s *from, struct local_state_s *to, struct usercmd_s *cmd, int runfuncs, double time, unsigned int random_seed);
int Hooked_HUD_Init(void);
struct cl_entity_s *Hooked_HUD_GetUserEntity( int index );
void Hooked_HUD_PlayerMoveInit ( struct playermove_s * move);
char Hooked_HUD_PlayerMoveTexture ( char *pTex );
void Hooked_IN_MouseEvent( int mstate );
void Hooked_IN_Accumulate( void );
void Hooked_IN_ActivateMouse( void );
void Hooked_IN_ClearStates( void );
void Hooked_IN_DeactivateMouse( void );
void Hooked_CL_CameraOffset( float *ofs );
int Hooked_CL_IsThirdPerson( void );
void Hooked_Demo_ReadBuffer( int size, unsigned char *buffer );
int Hooked_HUD_ConnectionlessPacket( struct netadr_s *net_from, const char *args, char *response_buffer, int *response_buffer_size );
void Hooked_HUD_CreateEntities( void );
void Hooked_HUD_DrawNormalTriangles( void );
void Hooked_HUD_DrawTransparentTriangles( void );
void Hooked_HUD_Frame( double time );
int Hooked_HUD_GetHullBounds( int hullnumber, float *mins, float *maxs );
struct cl_entity_s *HUD_GetUserEntity( int index );
void Hooked_HUD_ProcessPlayerState( struct entity_state_s *dst, const struct entity_state_s *src );
int Hooked_HUD_Reset( void );
void Hooked_HUD_Shutdown( void );
void Hooked_HUD_StudioEvent( const struct mstudioevent_s *event, const struct cl_entity_s *entity );
void Hooked_HUD_TxferLocalOverrides( struct entity_state_s *state, const struct clientdata_s *client );
void Hooked_HUD_TxferPredictionData( struct entity_state_s *ps, const struct entity_state_s *pps, struct clientdata_s *pcd, const struct clientdata_s *ppcd, struct weapon_data_s *wd, const struct weapon_data_s *pwd );
int Hooked_HUD_UpdateClientData( client_data_t *cdata, float flTime );
int Hooked_HUD_VidInit( void );
